export enum ASSETS {
  FETCH = 'FETCH_ASSETS',
  FETCH_BY_SYMBOL = 'FETCH_ASSETS_BY_SYMBOL',
  FETCH_BY_PROTOCOL_TYPE = 'FETCH_ASSETS_BY_PROTOCOL_TYPE',
  FETCH_BY_FILTER = 'FETCH_ASSETS_BY_FILTER',
}

export enum BALANCES {
  PORTFOLIO = 'TOTAL_WALLET_BALANCE',
  BALANCE = 'TOKEN_BALANCES',
}

export enum TRANSACTIONS {
  FETCH = 'FETCH_TRANSACTIONS',
}

export enum TOKENS {
  FETCH_LIST = 'FETCH_TOKEN_LIST',
}

export enum LOOPING_STRATEGY {
  FETCH = 'FETCH_LOOPING_STRATEGY',
  FETCH_BY_ID = 'FETCH_LOOPING_STRATEGY_BY_SYMBOL',
  FETCH_QUOTE_BY_ID = 'FETCH_LOOPING_STRATEGY_QUOTE_BY_SYMBOL',
  FETCH_LIFI_QUOTE_BY_ID = 'FETCH_LOOPING_STRATEGY_LIFI_QUOTE_BY_SYMBOL',
  CREATE_POSITION = 'CREATE_POSITION',
  MODIFY_POSITION = 'MODIFY_POSITION',
  UPDATE_POSITION_BY_ID = 'UPDATE_POSITION_BY_ID',
  FETCH_USER_POSITIONS = 'FETCH_USER_POSITIONS',
  FETCH_USER_POSITION_BY_ID = 'FETCH_USER_POSITION_BY_ID',
}
