export enum ASSETS {
  FETCH = 'FETCH_ASSETS',
  FETCH_BY_SYMBOL = 'FETCH_ASSETS_BY_SYMBOL',
}

export enum BALANCES {
  PORTFOLIO = 'TOTAL_WALLET_BALANCE',
  BALANCE = 'TOKEN_BALANCES',
}

export enum TRANSACTIONS {
  FETCH = 'FETCH_TRANSACTIONS',
}

export enum TOKENS {
  FETCH_LIST = 'FETCH_TOKEN_LIST',
}
