export enum ASSETS {
  FETCH = 'FETCH_ASSETS',
  FETCH_BY_SYMBOL = 'FETCH_ASSETS_BY_SYMBOL',
  FETCH_BY_PROTOCOL_TYPE = 'FETCH_ASSETS_BY_PROTOCOL_TYPE',
  FETCH_BY_FILTER = 'FETCH_ASSETS_BY_FILTER',
}

export enum BALANCES {
  PORTFOLIO = 'TOTAL_WALLET_BALANCE',
  BALANCE = 'TOKEN_BALANCES',
}

export enum TRANSACTIONS {
  FETCH = 'FETCH_TRANSACTIONS',
}

export enum TOKENS {
  FETCH_LIST = 'FETCH_TOKEN_LIST',
}

export enum LOOPING_POSITIONS {
  FETCH = 'LOOPING_POSITIONS',
}
